version: '2'
services:
  jhipster_small_test-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/JHipster_Small_Test/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=JHipster_Small_Test
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
